/**
 * Vite port of lib/feature-plugin.js
 * Auto-generates the features-worker entry and client bridge files
 * by scanning src/features/ for worker and meta files.
 */
import * as path from 'path';
import { posix } from 'path';
import { promises as fsp } from 'fs';
import { glob } from 'tinyglobby';
import type { Plugin } from 'vite';

const autoGenComment =
  '// This file is autogenerated by lib/vite-feature-plugin.ts\n';

let previousWorkerImports: string | undefined;
let previousJoinedMetas: string | undefined;

async function generateWorkerFile(workerImports: string[]) {
  const workerBasePath = path.join(process.cwd(), 'src', 'features-worker');

  const featuresWorkerTsNames = workerImports.map((tsImport) => [
    path.relative(workerBasePath, tsImport).split(path.sep).join(posix.sep),
    path.basename(tsImport),
  ]);

  const workerFile = [
    autoGenComment,
    `import { expose } from 'comlink';`,
    `import { timed } from './util';`,
    featuresWorkerTsNames.map(([p, name]) => `import ${name} from './${p}';`),
    `const exports = {`,
    featuresWorkerTsNames.map(([_, name]) => [
      `  ${name}(`,
      `    ...args: Parameters<typeof ${name}>`,
      `  ): ReturnType<typeof ${name}> {`,
      `    return timed('${name}', () => ${name}(...args));`,
      `  },`,
    ]),
    `};`,
    `export type ProcessorWorkerApi = typeof exports;`,
    `// 'as any' to work around the way our client code has insight into worker code`,
    `expose(exports, self as any);`,
  ]
    .flat(Infinity as 10)
    .join('\n');

  await fsp.writeFile(path.join(workerBasePath, 'index.ts'), workerFile);
}

async function generateWorkerBridge(workerImports: string[]) {
  const workerBridgeBasePath = path.join(
    process.cwd(),
    'src',
    'client',
    'lazy-app',
    'worker-bridge',
  );

  const featuresWorkerBridgeTsNames = workerImports.map((tsImport) => [
    path
      .relative(workerBridgeBasePath, tsImport)
      .split(path.sep)
      .join(posix.sep),
    path.basename(tsImport),
  ]);

  const bridgeMeta = [
    autoGenComment,
    featuresWorkerBridgeTsNames.map(
      ([p, name]) => `import type ${name} from '${p}';`,
    ),
    `export const methodNames = ${JSON.stringify(
      featuresWorkerBridgeTsNames.map(([_, name]) => name),
      null,
      '  ',
    )} as const;`,
    `export interface BridgeMethods {`,
    featuresWorkerBridgeTsNames.map(([_, name]) => [
      `  ${name}(`,
      `    signal: AbortSignal,`,
      `    ...args: Parameters<typeof ${name}>`,
      `  ): Promise<ReturnType<typeof ${name}>>;`,
    ]),
    `}`,
  ]
    .flat(Infinity as 10)
    .join('\n');

  await fsp.writeFile(path.join(workerBridgeBasePath, 'meta.ts'), bridgeMeta);
}

async function generateWorkerFiles() {
  const workerImports = (
    await glob('src/features/*/**/worker/*.ts', { absolute: true })
  )
    .filter((tsFile) => !tsFile.endsWith('.d.ts'))
    .map((tsFile) => tsFile.slice(0, -'.ts'.length));

  const joinedWorkerImports = workerImports.join();

  // Avoid regenerating if nothing changed (prevents infinite loop in watcher)
  if (joinedWorkerImports === previousWorkerImports) return;
  previousWorkerImports = joinedWorkerImports;

  await Promise.all([
    generateWorkerFile(workerImports),
    generateWorkerBridge(workerImports),
  ]);
}

async function generateFeatureMeta() {
  const getTsFiles = (pattern: string) =>
    glob(pattern, { absolute: true }).then((paths) =>
      paths
        .filter((tsFile) => !tsFile.endsWith('.d.ts'))
        .map((tsFile) => tsFile.slice(0, -'.ts'.length)),
    );

  const metas = await Promise.all(
    [
      'src/features/encoders/*/shared/meta.ts',
      'src/features/processors/*/shared/meta.ts',
      'src/features/preprocessors/*/shared/meta.ts',
    ].map((pattern) => getTsFiles(pattern)),
  );

  const [encoderMetas, processorMetas, preprocessorMetas] = metas;

  const featureMetaBasePath = path.join(
    process.cwd(),
    'src',
    'client',
    'lazy-app',
    'feature-meta',
  );

  const joinedMetas = metas.flat().join();

  // Avoid regenerating if nothing changed
  if (joinedMetas === previousJoinedMetas) return;
  previousJoinedMetas = joinedMetas;

  const getTsName = (tsImport: string): [string, string] => [
    path
      .relative(featureMetaBasePath, tsImport)
      .split(path.sep)
      .join(posix.sep),
    path.basename(tsImport.slice(0, -'/shared/meta'.length)),
  ];

  const encoderMetaTsNames = encoderMetas.map(getTsName);
  const processorMetaTsNames = processorMetas.map(getTsName);
  const preprocessorMetaTsNames = preprocessorMetas.map(getTsName);

  const featureMeta = [
    autoGenComment,
    // Encoder stuff
    encoderMetaTsNames.map(
      ([p, name]) => `import * as ${name}EncoderMeta from '${p}';`,
    ),
    encoderMetaTsNames.map(
      ([p, name]) =>
        `import * as ${name}EncoderEntry from '${p.replace(
          /shared\/meta$/,
          'client',
        )}';`,
    ),
    `export type EncoderState =`,
    encoderMetaTsNames.map(
      ([_, name]) =>
        `  | { type: "${name}", options: ${name}EncoderMeta.EncodeOptions }`,
    ),
    `;`,
    `export type EncoderOptions =`,
    encoderMetaTsNames.map(
      ([_, name]) => `  | ${name}EncoderMeta.EncodeOptions`,
    ),
    `;`,
    `export const encoderMap = {`,
    encoderMetaTsNames.map(
      ([_, name]) =>
        `  ${name}: { meta: ${name}EncoderMeta, ...${name}EncoderEntry },`,
    ),
    `};`,
    `export type EncoderType = keyof typeof encoderMap`,
    // Processor stuff
    processorMetaTsNames.map(
      ([p, name]) => `import * as ${name}ProcessorMeta from '${p}';`,
    ),
    `interface Enableable { enabled: boolean; }`,
    `export interface ProcessorOptions {`,
    processorMetaTsNames.map(
      ([_, name]) => `  ${name}: ${name}ProcessorMeta.Options;`,
    ),
    `}`,
    `export interface ProcessorState {`,
    processorMetaTsNames.map(
      ([_, name]) => `  ${name}: Enableable & ${name}ProcessorMeta.Options;`,
    ),
    `}`,
    `export const defaultProcessorState: ProcessorState = {`,
    processorMetaTsNames.map(
      ([_, name]) =>
        `  ${name}: { enabled: false, ...${name}ProcessorMeta.defaultOptions },`,
    ),
    `}`,
    // Preprocessor stuff
    preprocessorMetaTsNames.map(
      ([p, name]) => `import * as ${name}PreprocessorMeta from '${p}';`,
    ),
    `export interface PreprocessorState {`,
    preprocessorMetaTsNames.map(
      ([_, name]) => `  ${name}: ${name}PreprocessorMeta.Options,`,
    ),
    `}`,
    `export const defaultPreprocessorState: PreprocessorState = {`,
    preprocessorMetaTsNames.map(
      ([_, name]) => `  ${name}: ${name}PreprocessorMeta.defaultOptions,`,
    ),
    `};`,
  ]
    .flat(Infinity as 10)
    .join('\n');

  await fsp.writeFile(path.join(featureMetaBasePath, 'index.ts'), featureMeta);
}

export function featurePlugin(): Plugin {
  return {
    name: 'feature-plugin',
    async buildStart() {
      await Promise.all([generateWorkerFiles(), generateFeatureMeta()]);
    },
  };
}
